### PR TITLE
Updated cadmium-playercore to 6.0044.268.911

### PR DESCRIPTION
**Pull request by zackmark29**

### CODE REVIEW

**Comment by lkmvip** [comment]
no update required

**Comment by inalam** [comment]
i got that error in chrome and edge tho. i've tried your PR zack in chrome.it works but show less menu than lkmvip original and somehow i got 1k bitrate using extension (the codecs wont change in the info stays at vp9) and 2k bitrate without extension (av1 prk)

**Comment by Phoenomenal** [comment]
Same problem on Windows 11 23h2.  Use other extension for the time being, like netflix international (its basically the same minus ddplus option, still has 5.1 sound but lover quality codec)  With Netflix its always good to have backup extension not the first time that one extension stop working and other still works. (it will be fixed eventually either by itself or with new update. Not the first time this happens and definitely not the last....)

**Comment by erickyun** [comment]
> netflix international

Which repo? Is it this one? https://github.com/shirt-dev/netflix-international

**Pull request closed without merging**
